### ISSUE TITLE
mode = 'supervised'

### ISSUE THREAD

**Issue by wh-isper** [tadeephuy/CoFo#3]
Dear, author! Thanks for your code, and I reimplemented the result in the paper. But I have some doubts. In your paper, the setting is unsupervised domain adaptation, which means labels on the target domain are unavailable. 
    But in your code, you set mode='supervised', and use labels y that mix source labels and target labels to compute dice loss.
![image](https://user-images.githubusercontent.com/89512441/222327713-ef668be1-337a-4966-b54f-3d48f3ba2bb6.png)
    Even though setting mode='unsupervised', it still uses y to compute dice loss. And there is a mint_ent_loss which is not mentioned in the paper.
![image](https://user-images.githubusercontent.com/89512441/222328384-9a08cdda-07da-4a15-8f57-fdaf671708c8.png)
    Maybe I  misunderstood the code. Could you please kindly resolve my doubt?

**Comment by wh-isper** [comment]
Sorry for the wrong markdown format

**Comment by tdh512194** [comment]
I tried the mint ent loss from the FDA paper https://arxiv.org/abs/2004.05498 . The target masks are actually predicted masks but should have been computed on the fly. The results was not good compared to without using it so I figured I would just dont include it.

Sorry for your inconvenience! I realized that this code is from a wrong branch where I didnt remove it.  I will try to fix this asap! In the mean time, can you try first with the supervised settings?

**Comment by wh-isper** [comment]
Thanks for your reply！
