### ISSUE TITLE
can't reimplement the results on Kvasir->ETIS

### ISSUE THREAD

**Issue by wh-isper** [tadeephuy/CoFo#4]
Setting mode = 'unsupervised', I  can reimplement the results on Kvasir->Endo,  but I got dice=49.6 on Kvasir->ETIS

**Comment by tdh512194** [comment]
Sorry for your inconvenience! I realized that this code is from a wrong branch where I didnt remove it. I will try to fix this asap! In the mean time, can you try first with the supervised settings or with other datasets as I figured ETIS is quite tricky compared to others.
