### ISSUE TITLE
about dataset split

### ISSUE THREAD

**Issue by lllzzzrrr** [tadeephuy/CoFo#6]
Dear author, CVC-Endo dataset is officially splilt into 547:183:182 for train:valid:test. So  I think official training data 547 should be target training data when CVC is target domain, but in your code, official valid data 183 is set to be target domain data. So does Kvasir. I am little confused about that.

**Comment by tdh512194** [comment]
Hi @lllzzzrrr, we only use valid data for the adaptation step, notthe whole training set. This is to mimic the real scenario where labelled target domain data are not always abundant.
